[licenses]
unlicensed = "deny"

allow = [
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-3-Clause",
    "ISC",
    "MIT",
    "MPL-2.0",
]

exceptions = [
    { allow = [
        "Unicode-DFS-2016"
    ], name = "unicode-ident" },
]

