import os

Decider('content-timestamp')
SetOption('num_jobs', 8)

env = Environment()

term = os.environ.get('TERM') # for color
if term is not None:
    env['ENV']['TERM'] = term

Export('env')

SConscript('SConscript', variant_dir='build', duplicate=0)
