[package]
name = "opencan-cli"
version = "0.1.0"
license = "MPL-2.0"
edition = "2021"

[dependencies]
anyhow = "1.0.69"
opencan-codegen = { path = "../codegen" }
opencan-compose = { path = "../compose" }
clap = "4.1.4"
