[package]
name = "opencan-cli"
version = "0.1.0"
license = "MPL-2.0"
edition = "2021"

[dependencies]
anyhow = "1.0.68"
opencan-analyze = { path = "../analyze" }
opencan-codegen = { path = "../codegen" }
opencan-compose = { path = "../compose" }
clap = "4.1.8"
