[package]
name = "opencan-codegen"
version = "0.1.0"
license = "MPL-2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.68"
chrono = { version = "0.4.23", features = ["clock", "std"], default-features = false }
clap = { version = "4.0.32", features = ["cargo"] }
indoc = "1.0.8"
textwrap = { version = "0.16.0", default-features = false }

opencan-core = { path = "../core" }

[dev-dependencies]
cc = "1.0.78"
libloading = "0.7.4"
pyo3 = { version = "0.17.3", features = ["auto-initialize"] }
semver = "1.0.16"
tempdir = "0.3.7"
