[package]
name = "opencan-compose"
version = "0.1.0"
license = "MPL-2.0"
edition = "2021"

[dependencies]
anyhow = "1.0.68"
clap = { version = "4.1.8", features = ["derive"] }
indoc = "2.0.0"
serde = { version = "1.0.153", features = ["derive"] }
serde_json = "1.0.93"
serde_yaml = "0.9.17"

opencan-core = { path = "../core" }
