[package]
name = "opencan-compose"
version = "0.1.0"
license = "MPL-2.0"
edition = "2021"

[dependencies]
anyhow = "1.0.68"
opencan-core = { path = "../core" }
clap = { version = "4.0.32", features = ["derive"] }
indoc = "1.0.8"
thiserror = "1.0.38"
serde = { version = "1.0.151", features = ["derive"] }
serde_json = "1.0.91"
serde_yaml = "0.9.16"

[lib]
path = "src/lib.rs"
